# Generated by Django 5.2 on 2025-05-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Budget_Line', models.CharField(max_length=100)),
                ('SDA', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('Cost_Category', models.CharField(max_length=100)),
                ('Budget', models.CharField(max_length=100)),
                ('Actual', models.CharField(max_length=100)),
                ('Varience', models.CharField(max_length=100)),
            ],
        ),
    ]
